### ISSUE TITLE
Could not find a version that satisfies the requirement batchdist; No matching distribution found for batchdist

### ISSUE THREAD

**Issue by NooneBug** [mi92/batchdist#1]
When I try to install the package with `pip install batchdist` the terminal shows me 2 errors: 

```
ERROR: Could not find a version that satisfies the requirement batchdist
ERROR: No matching distribution found for batchdist
```

This happens even in a clean new environment

Are there other methods to install the package?

**Comment by mi92** [comment]
Thanks for pointing this out! The problem was with the unittest dependency. I removed it as it is in the standard library anyways and pushed a new version (0.1.3). 
In general, I work with poetry, so I also added the corresponding installation option to the Readme (poetry add batchdist).

I hope this solves the issue 👍
